################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
- sections:
  - title: Authorization
    link: docs/Authorization.md
- sections:
  - title: Account Maintenance
    link: docs/AM.md
    sections:
    - title: Merchant Inquiry
      link: docs/AM/MerchantInquiry.md
    - title: Merchant Update
      link: docs/AM/MerchantUpdate.md
    - title: Equipment Search
      link: docs/AM/EquipmentSearch.md
    - title: Equipment Boarding
      link: docs/AM/EquipmentBoarding.md
    - title: Equipment Update
      link: docs/AM/EquipmentUpdate.md
- sections:
  - title: Boarding
    link: docs/Boarding.md
    sections:
    - title: North FACS
      link: docs/Boarding/FACS.md
    - title: North FDS
      link: docs/Boarding/FDS.md
    - title: Omaha
      link: docs/Boarding/Omaha.md
- sections:
  - title: Reporting
    link: docs/Reporting.md
    sections:
    - title: Reporting 1
      link: docs/Reporting/start.md
    - title: Reporting 2
      link: docs/Reporting/start.md
    - title: Reporting 3
      link: docs/Reporting/start.md
    - title: Reporting 4
      link: docs/Reporting/start.md
