################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    articles:
      - title: Welcome to AccessOne API Suite
        link: docs/getting-started.md
  - title: Usage Guides for Boarding and Reporting
    sections:
      - title: North Boarding
        sections:
          - title: introduction
            link: docs/N-2.0-introduction.md
          - title: Technical Specifications
            link: docs/N-3.0-Technical-Specifications.md
            sections:
              - title: Boarding API Methods
                link: docs/N-3.1-Boarding-API-Methods.md
              - title: XML Format
                link: docs/N-3.2-XML-Format.md
              - title: Validation Handler
                link: docs/N-3.3-Validation-Handler.md
              - title: MPA Status Report
                link: docs/N-3.4-MPA-Status-Report.md
              - title: Boarding Process
                link: docs/N-3.5-Boarding-Process.md
          - title: SOAP Security Guide
            link: docs/N-4.0-SOAP-Security-Guide.md
            sections:
              - title: Verification via SOAP UI
                link: docs/N-4.1-Verification-Via-SOAP-UI.md
              - title: Connectivity Verification Via Other Platforms
                link: docs/N-4.2-Connectivity-Via-Other-Platforms.md
              - title: Common Connectivity Issues
                link: docs/N-4.3-Common-Connectivity-Issues
          - title: Basic Verification Guide
            link: docs/N-5.0-Basic-Verification-Guide.md
            sections:
              - title: Preparations
                link: docs/N-5.1-Preparations.md
              - title: Merchant Application Submission
                link: docs/N-5.2-Merchant-Application-Submission.md
              - title: Post Merchant Submission
                link: docs/N-5.3-Post-Merchant-Submission.md
              - title: MPA Status Tracking
                link: docs/N-5.4-MPA-Status-Tracking.md
      - title: Optis Boarding
        sections:
          - title: Introduction
            link: docs/O-1.0-Introduction.md
          - title: Requirements
            link: docs/O-2.0-Requirements.md
          - title: Request Format
            link: docs/O-3.0-Request-Format.md
            section:
              - title: Soap Envelope
                link: docs/O-3.1-Soap-Envelope.md
              - title: Using Master Merchant Document
                link: docs/O-3.2-Using-Master-Mercant-Document.md
          - title: WS Security Authentication
            link: docs/O-4.0-WS-Security-Authentication.md
            section:
              - title: Soap UI Project
                link: docs/O-4.1-Soap-UI-Project.md
          - title: Boarding API Methods
            link: docs/O-5.0-Boarding-API-Methods.md
            section:
              - title: Submit MPA Method
                link: docs/O-5.1-Submit-MPA-Method.md
              - title: Get Status By Time Span Method
                link: docs/O-5.2-Get-Status-By-Time-Span-Method.md
              - title: Retrieve MPA Testing Support
                link: docs/O-5.3-Retrieve-MPA-Testing-Support.md
              - title: MPA Status Reporting
                link: docs/O-5.4-MPA-Status-Reporting.md
              - title: Merchant Information XML Format
                link: docs/O-5.5-Merchant-Information-XML-Format.md
              - title: Merchant Information Validation Handler
                link: docs/O-5.6-Merchant-Validation-Handler.md
              - title: Conditional Data Logic
                link: docs/O-5.7-Conditional-Data-Logic.md
          - title: High Level Test Cases
            section:
              - title: Starting XML File
                link: docs/O-6.1-Starting-XML-File.md
              - title: Common Issues
                link: docs/O-6.2-Common-Issues.md
              - title: Post MPA Submission Checks
                link: docs/O-6.3-Post-MPA-Submission-Checks.md
              - title: Front End Data
                link: docs/O-6.4-Front-End-Data.md
              - title: Stored Data
                link: docs/O-6.5-Stored-Data.md
              - title: Exported PDFs
                link: docs/O-6.6-Exported-PDFs.md
          - title: SOAP Request Guide
            section:
              - title: Prerequisite Checks
                link: docs/O-7.1-Prerequisite-Checks.md
              - title: Configuring SOAP UI
                link: docs/O-7.2-Configuring-SOAP-UI.md
          - title: Submitting SOAP Requests
            section:
              - title: Web Method Submit MPA
                link: docs/O-8.1-Web-Method-Submit-MPA.md
              - title: Web Method Retrieve MPA XML
                link: docs/O-8.2-Web-Method-Retrieve-MPA-XML.md
              - title: Web Method Get Status By Time Span
                link: docs/O-8.3-Web-Method-Get-Status-By-Time-Span.md
              - title: Web Method Get Status By Time Span
                link: docs/O-8.3-Web-Method-Get-Status-By-Time-Span.md
          - title: Connectivity Via An External Tool
            link: docs/O-9.0-Connectivity-Via-An-External-Tool.md
          - title: SOAP Request Header
            section:
              title: SOAP Header Structure
              link: docs/O-10.1-SOAP-Header-Structure.md
              title: SOAP Header Example
              link: docs/O-10.2-SOAP-Header-Example.md
          - title: SOAP Request Body
            section:
              title: SOAP Body Structure
              link: docs/O-11.1-SOAP-Body-Structure.md
              title: SOAP Body Example
              link: docs/O-11.2-SOAP-Body-Example.md
          - title: Common Issues
            section:
              - title: Generic Error
                link: docs/O-12.1-Generic-Error.md
              - title: Submission Failure With Specific Errors
                link: docs/O-12.2-Submission-Failure-With-Specific-Errors.md
              - title: Submission Failure Without Specific Errors
                link: docs/O-12.3-Submission-Failure-Without-Specific-Errors.md
      - title: Reporting
        link: docs/reporting-api-specifications.md
