################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
    articles:
      - title: Welcome to AccessOne API Suite
        link: docs/getting-started.md
  - title: Usage Guides for Boarding and Reporting
    sections:
      - title: North Boarding
        sections:
          - title: introduction
            link: docs/2.0-introduction.md
          - title: Technical Specifications
            link: docs/3.0-Technical-Specifications.md
            sections:
              - title: Boarding API Methods
                link: docs/3.1-Boarding-API-Methods.md
              - title: XML Format
                link: docs/3.2-XML-Format.md
              - title: Validation Handler
                link: docs/3.3-Validation-Handler.md
              - title: MPA Status Report
                link: docs/3.4-MPA-Status-Report.md
              - title: Boarding Process
                link: docs/3.5-Boarding-Process.md
          - title: SOAP Security Guide
            link: docs/4.0-SOAP-Security-Guide.md
            sections:
              - title: Verification via SOAP UI
                link: docs/4.1-Verification-Via-SOAP-UI.md
              - title: Connectivity Verification Via Other Platforms
                link: docs/4.2-Connectivity-Via-Other-Platforms.md
              - title: Common Connectivity Issues
                link: docs/4.3-Common-Connectivity-Issues
          - title: Basic Verification Guide
            link: docs/5.0-Basic-Verification-Guide.md
            sections:
              - title: Preparations
                link: docs/5.1-Preparations.md
              - title: Merchant Application Submission
                link: docs/5.2-Merchant-Application-Submission.md
              - title: Post Merchant Submission
                link: docs/5.3-Post-Merchant-Submission.md
              - title: MPA Status Tracking
                link: docs/5.4-MPA-Status-Tracking.md
      - title: Optis Boarding
        link: docs/optis-boarding-api-specifications.md
      - title: Reporting
        link: docs/reporting-api-specifications.md
