---
toc:
- section:
  - title: Getting Started
    link: getting-started/overview.md
    open: true
    section:
    - title: Setup a tenant
      link: getting-started/setup-tenant.md
      open: true
      article:
      - title: Setup tenant
        link: getting-started/setup-tenant.md
      - title: Deploy tenant
        link: getting-started/deploy-tenant.md
      - title: Register tenant
        link: getting-started/register-tenant.md
    - title: Create a tenant
      link: getting-started/create-tenant.md
      article:
      - title: Code tenant
        link: getting-started/code-tenant.md
      - title: Deploy tenant
        link: getting-started/deploy-tenant.md
      - title: Register tenant
        link: getting-started/register-tenant.md
